version: '3.7'

services:
  mvdsv:
    image: niclaslindstedt/nquakesv
    environment:
      - HOSTNAME=nQuake KTX Server
      - SERVER_IP= # this is your server's external ip, leave it empty to look up your external ip
      - PORT=27500 # this is the external port number for this server -- use it in the ports: section too
      - RCON_PASSWORD=secret
      - QTV_PASSWORD=
      - SERVER_ADMIN=anon <anonymous@example.com>
      - REPORT_URL=https://badplace.eu
      - REPORT_KEY=askmeag
    ports:
      - '27500:27500/udp' # this should match your PORT variable above, and should be the same on left & right
    volumes:
      - logs:/nquake/logs
      - media:/nquake/media
      - demos:/nquake/demos

  qtv:
    image: niclaslindstedt/qtv
    tty: true
    environment:
      - HOSTNAME=nQuake QTV
      - QTV_PASSWORD=
      - ADMIN_PASSWORD=secret
      - TARGET_SERVERS=mvdsv:27500 # comma-separated
    ports:
      - '28000:28000' # this always listens internally at port 28000
    volumes:
      - demos:/qtv/demos
      - media:/qtv/id1
    healthcheck:
      test: ["CMD", "/health_check.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s

  qwfwd:
    image: niclaslindstedt/qwfwd
    tty: true
    environment:
      - HOSTNAME=nQuake QWFWD
    ports:
      - '30000:30000/udp' # this always listens internally at port 30000

volumes:
  logs:
  demos:
  media:
