version: '3.7'

services:
  mvdsv:
    image: niclaslindstedt/nquakesv
    environment:
      - HOSTNAME=nquake server
      - LISTEN_PORT=28501
      - RCON_PASSWORD=changeme
      - QTV_STREAMPORT=28000
      - QTV_PASSWORD=changeme
      - SERVER_ADMIN=empezar <empezar@qkn.se>
      - REPORT_URL=https://badplace.eu
      - REPORT_KEY=askmeag
    ports:
      - '28501:28501/udp'
    volumes:
      - logs:/nquake/logs
      - media:/nquake/media
      - demos:/nquake/demos

  qtv:
    image: niclaslindstedt/qtv
    environment:
      - HOSTNAME=nquake qtv
      - LISTEN_PORT=28000
      - QTV_PASSWORD=changeme
      - TARGET_SERVERS=mvdsv:28501 # comma-separated
    ports:
      - '28000:28000'
      - '8989:80'
    volumes:
      - demos:/qtv/demos
      - media:/qtv/id1

  qwfwd:
    image: niclaslindstedt/qwfwd
    environment:
      - HOSTNAME=nquake qwfwd
      - LISTEN_IP=0.0.0.0
      - LISTEN_PORT=30000
    ports:
      - '30000:30000/udp'

volumes:
  logs:
  demos:
  media:
